AllCops:
  Exclude:
    - 'frontend/**/*'
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Lint/RescueException:
  Exclude:
    - 'backend/rollbar_interceptor.rb'

Metrics/LineLength:
  Max: 100

Style/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

Style/EndOfLine:
  Exclude:
    - '**/*'

