AllCops:
  Exclude:
    - 'frontend/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 80

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Lint/RescueException:
  Exclude:
    - 'backend/middleware/rollbar_interceptor.rb'

Style/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

Style/EndOfLine:
  Exclude:
    - '**/*'

