AllCops:
  Exclude:
    - 'frontend/**/*'
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Style/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

Style/EndOfLine:
  Exclude:
    - '**/*'
