test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

dev:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: nitpick
  pool: 5
  username: nitpick
  password: nitpick

production:
  adapter: postgresql
  encoding: unicode
  database: nitpick
  host: st
  port: 12345
  pool: 5
  username: nitpick
  password: nitpick
